-- This is used to populate the starting database for the rentcar project
-- It should be modified if any administration interfaces are available
-- All the tables are auto-generated by setting spring.jpa.hibernate.ddl-auto=update in application.properties

-- Clean up the old data in all the tables except reservation table, which has all the reservation records
-- It is to prevent inserting the following things again in the db;
-- Remove the delete when a table is no longer need to have start data
DELETE FROM inventory;
DELETE FROM cartype;
DELETE FROM user;
DELETE FROM partner;

-- start from 1 after cleanup
ALTER TABLE inventory AUTO_INCREMENT = 1;
ALTER TABLE user AUTO_INCREMENT = 1;
ALTER TABLE partner AUTO_INCREMENT = 1;

-- add some cartypes with their unique id
INSERT INTO cartype VALUES (1, "Standard");
INSERT INTO cartype VALUES (2, "SUV");
INSERT INTO cartype VALUES (3, "Truck");
INSERT INTO cartype VALUES (4, "Van");
INSERT INTO cartype VALUES (5, "Luxury");

-- Add some cars to the inventory
-- They can be commented out if there is an interface allows administrator to edit the cars inventory
--	carid: is primary key will be auto-generated
--	carTypeID: a foreign key reference to the cartypeid in cartype table
-- 	description, maxPassengers: are information about the car
--	location: the location of the car
--  image: an image file of the car located in the src/main/resources/static/images
--	dailyPrice and weeklyPrice: are the prices to rent the car
INSERT INTO inventory (carTypeID, description, maxPassengers, location, image, dailyPrice, weeklyPrice) VALUES
(1, "Volkswagen Jetta, Toyota Corolla or similar. Features: Cruise Control, AM/FM Stereo Radio, Automatic, 
Air Conditioning, and Bluetooth.", 5, "Boston", "standard.png", 51.25, 305.50),
(1, "Volkswagen Jetta, Toyota Corolla or similar. Features: Cruise Control, AM/FM Stereo Radio, Automatic, 
Air Conditioning, and Bluetooth.", 5, "Boston", "standard.png", 51.25, 305.50),
(1, "Volkswagen Jetta, Toyota Corolla or similar. Features: Cruise Control, AM/FM Stereo Radio, Automatic, 
Air Conditioning, and Bluetooth.", 5, "Miami", "standard.png", 51.25, 305.50),
(1, "Volkswagen Jetta, Toyota Corolla or similar. Features: Cruise Control, AM/FM Stereo Radio, Automatic, 
Air Conditioning, and Bluetooth.", 5, "Miami", "standard.png", 51.25, 305.50),
(1, "Volkswagen Jetta, Toyota Corolla or similar. Features: Cruise Control, AM/FM Stereo Radio, Automatic, 
Air Conditioning, and Bluetooth.", 5, "New York", "standard.png", 51.25, 305.50),
(1, "Volkswagen Jetta, Toyota Corolla or similar. Features: Cruise Control, AM/FM Stereo Radio, Automatic, 
Air Conditioning, and Bluetooth.", 5, "New York", "standard.png", 51.25, 305.50),
(1, "Volkswagen Jetta, Toyota Corolla or similar. Features: Cruise Control, AM/FM Stereo Radio, Automatic, 
Air Conditioning, and Bluetooth.", 5, "Las Vegas", "standard.png", 51.25, 305.50),
(1, "Volkswagen Jetta, Toyota Corolla or similar. Features: Cruise Control, AM/FM Stereo Radio, Automatic, 
Air Conditioning, and Bluetooth.", 5, "Las Vegas", "standard.png", 51.25, 305.50),
(1, "Volkswagen Jetta, Toyota Corolla or similar. Features: Cruise Control, AM/FM Stereo Radio, Automatic, 
Air Conditioning, and Bluetooth.", 5, "San Francisco", "standard.png", 51.25, 305.50),
(1, "Volkswagen Jetta, Toyota Corolla or similar. Features: Cruise Control, AM/FM Stereo Radio, Automatic, 
Air Conditioning, and Bluetooth.", 5, "San Francisco", "standard.png", 51.25, 305.50),
(2, "Nissan Rogue or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "Boston", "suv.png", 63.60, 350.25),
(2, "Nissan Rogue or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "Boston", "suv.png", 63.60, 350.25),
(2, "Nissan Rogue or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "Miami", "suv.png", 63.60, 350.25),
(2, "Nissan Rogue or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "Miami", "suv.png", 63.60, 350.25),
(2, "Nissan Rogue or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "Las Vegas", "suv.png", 63.60, 350.25),
(2, "Nissan Rogue or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "New York", "suv.png", 63.60, 350.25),
(2, "Nissan Rogue or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "San Francisco", "suv.png", 63.60, 350.25),
(3, "Ford F150, Chevy Colorado or similar. Features: Cruise Control, AM/FM Stereo Radio, 
Automatic, Air Conditioning, and Bluetooth.", 4, "Boston", "truck.png", 85.50, 480.25),
(3, "Ford F150, Chevy Colorado or similar. Features: Cruise Control, AM/FM Stereo Radio, 
Automatic, Air Conditioning, and Bluetooth.", 4, "Miami", "truck.png", 85.50, 480.25),
(3, "Ford F150, Chevy Colorado or similar. Features: Cruise Control, AM/FM Stereo Radio, 
Automatic, Air Conditioning, and Bluetooth.", 4, "Las Vegas", "truck.png", 85.50, 480.25),
(3, "Ford F150, Chevy Colorado or similar. Features: Cruise Control, AM/FM Stereo Radio, 
Automatic, Air Conditioning, and Bluetooth.", 4, "New York", "truck.png", 85.50, 480.25),
(3, "Ford F150, Chevy Colorado or similar. Features: Cruise Control, AM/FM Stereo Radio, 
Automatic, Air Conditioning, and Bluetooth.", 4, "San Francisco", "truck.png", 85.50, 480.25),
(4, "Chrysler Pacifica or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 7, "Boston", "van.png", 105.25, 600.25),
(4, "Chrysler Pacifica or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 7, "Miami", "van.png", 105.25, 600.25),
(4, "Chrysler Pacifica or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 7, "New York", "van.png", 105.25, 600.25),
(4, "Chrysler Pacifica or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 7, "Las Vegas", "van.png", 105.25, 600.25),
(4, "Chrysler Pacifica or similar. Features: Cruise Control, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 7, "San Francisco", "van.png", 105.25, 600.25),
(5, "BMW 7 Series , Mercedes Benz S Class , Porsche Panamera or similar. Features: Cruise Control, Leather interior, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "Boston", "luxury.png", 130.00, 700.25),
(5, "BMW 7 Series , Mercedes Benz S Class , Porsche Panamera or similar. Features: Cruise Control, Leather interior, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "Miami", "luxury.png", 130.00, 700.25),
(5, "BMW 7 Series , Mercedes Benz S Class , Porsche Panamera or similar. Features: Cruise Control, Leather interior, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "Las Vegas", "luxury.png", 130.00, 700.25),
(5, "BMW 7 Series , Mercedes Benz S Class , Porsche Panamera or similar. Features: Cruise Control, Leather interior, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "New York", "luxury.png", 130.00, 700.25),
(5, "BMW 7 Series , Mercedes Benz S Class , Porsche Panamera or similar. Features: Cruise Control, Leather interior, 
AM/FM Stereo Radio, Automatic, Air Conditioning, and Bluetooth.", 5, "San Francisco", "luxury.png", 130.00, 700.25);

-- Add some users to start for testing purpose, especially when the user registration interface is not ready
-- They can be commented out if there is an interface to create users
-- useid: is the primary key and auto-generated
-- emailAddress: is the user's emailAddress, expected to be unique key and used to log in 
-- password: is the user's password to log in
-- creditNumber: is the user's credit number to pay the rental
-- address: is user's home address
INSERT INTO user (emailAddress, name, password, creditNumber, address) VALUES
("bob@gmail.com", "Bob", "bob_pwd", "123456", "bob home address"),
("sue@gmail.com", "Sue", "sue_pwd", "234567", "sue home address");

-- Add some business partner, which allows to make request to book a car
-- companyid: is the primary key and auto-generated; it is used to identified the company
-- name: is the partner company's business name
-- discountRate: is between 0 to 1.0 to give a discount to the business partner when renting cars
--		0 means free; 1.0 means full price - no discount
INSERT INTO partner(name, discountRate) VALUES
("Cheap Trip", 0.7),
("Happy Traveller", 0.8);

-- resevation table does not need start data, records will be created/deleted by user or business partner
-- reservation (reserveID, carID, startDate, endDate, userID, companyID, totalPrice, location)
-- 	reserveID: primary key, auto-generated, used as a reference number to retreive info or to cancel
--	carID: an id to identified the rental car and retreive info about the car in inventory table
--	startDate: the starting date of the reseved car
--	endDate: the last date or drop off date of reserved car
--	userID: an id if > 0 to identify the user who rented the car
--  comapanyID: an id if > 0 to identify the business partner which rented the car
--	totalPrice: the total price that has to be paid for the rental
--	location: the location where the car is to pickup and drop off
